{"name": "test_login", "status": "broken", "statusDetails": {"message": "NameError: name 'init_login' is not defined", "trace": "self = <PrimarySelenium.case.login.test_login_case.TestLoginCase object at 0x03D82C70>\n\n    @pytest.mark.login\n    @pytest.mark.usefixtures(\"init_driver\")\n    def test_login(self):\n>       init_login.click_forget_pwd_link()\nE       NameError: name 'init_login' is not defined\n\ncase\\login\\test_login_case.py:36: NameError"}, "attachments": [{"name": "log", "source": "de062e4a-f13a-4cd5-b202-9df2a83764dc-attachment.txt", "type": "text/plain"}], "start": 1597293404765, "stop": 1597293404765, "uuid": "1e6b34a0-e9c2-4301-b734-cf8e912125ef", "historyId": "5962709e675f4f4e1376f8ee83b33490", "testCaseId": "5f4a0dfd943dd3927afc6230a6eae707", "fullName": "case.login.test_login_case.TestLoginCase#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "case.login"}, {"name": "suite", "value": "test_login_case"}, {"name": "subSuite", "value": "TestLoginCase"}, {"name": "host", "value": "FYYX-2019VXOSDQ"}, {"name": "thread", "value": "13900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.login.test_login_case"}]}