{"name": "test_login_password_error_case", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False\n  +True\n  -False", "trace": "self = <PrimarySelenium.case.login.test_login_case.TestLoginCase object at 0x03DA9748>, init_login = <bussiness.login_bussiness.LoginBussiness object at 0x03DAE4F0>\n\n    @pytest.mark.login\n    @pytest.mark.usefixtures(\"init_driver\")\n    def test_login_password_error_case(self, init_login):\n    \n        init_login.login_eshop(\"13544989573\", \"111111\")\n>       assert init_login.check_login_fail() == False\nE       assert True == False\nE         +True\nE         -False\n\ncase\\login\\test_login_case.py:25: AssertionError"}, "attachments": [{"name": "log", "source": "c67edec7-73c5-4b4a-8780-735426c378fd-attachment.txt", "type": "text/plain"}], "start": 1597503149166, "stop": 1597503150927, "uuid": "95df9eef-e29a-424b-8a0f-21e287c830a3", "historyId": "8c75e61dfeaf40e00fbf3596d8f857c6", "testCaseId": "e31b71ea53c9108f5a105705e791d0a6", "fullName": "case.login.test_login_case.TestLoginCase#test_login_password_error_case", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "case.login"}, {"name": "suite", "value": "test_login_case"}, {"name": "subSuite", "value": "TestLoginCase"}, {"name": "host", "value": "FYYX-2019VXOSDQ"}, {"name": "thread", "value": "16596-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.login.test_login_case"}]}